version: 2

publications:
  - url: https://packagist.org/packages/launchdarkly/server-sdk-consul
    description: Packagist

jobs:
  - template:
      name: php

branches:
  - name: main
  - name: 1.x

documentation:
  gitHubPages: true
  title: LaunchDarkly PHP SDK Consul integration
